// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1xUq31cWLSdS709UpfqjyMZNO8mtUIh0',
    appId: '1:1045161038439:web:9fec2cef5967d7a11fbac2',
    messagingSenderId: '1045161038439',
    projectId: 'slidesync-1',
    authDomain: 'slidesync-1.firebaseapp.com',
    storageBucket: 'slidesync-1.firebasestorage.app',
    measurementId: 'G-RT1YQ8QRBH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLK1tAa61E9elkYB5SKmqzffRkmcdNe9A',
    appId: '1:1045161038439:android:cc1e65749a9cf7eb1fbac2',
    messagingSenderId: '1045161038439',
    projectId: 'slidesync-1',
    storageBucket: 'slidesync-1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeiU2OMv18I7j8fDvlhSX6SsF2AMd6F2E',
    appId: '1:1045161038439:ios:3c04fd350be3b0001fbac2',
    messagingSenderId: '1045161038439',
    projectId: 'slidesync-1',
    storageBucket: 'slidesync-1.firebasestorage.app',
    iosBundleId: 'com.example.slidesSync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeiU2OMv18I7j8fDvlhSX6SsF2AMd6F2E',
    appId: '1:1045161038439:ios:3c04fd350be3b0001fbac2',
    messagingSenderId: '1045161038439',
    projectId: 'slidesync-1',
    storageBucket: 'slidesync-1.firebasestorage.app',
    iosBundleId: 'com.example.slidesSync',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1xUq31cWLSdS709UpfqjyMZNO8mtUIh0',
    appId: '1:1045161038439:web:880dc1fc67bdcb021fbac2',
    messagingSenderId: '1045161038439',
    projectId: 'slidesync-1',
    authDomain: 'slidesync-1.firebaseapp.com',
    storageBucket: 'slidesync-1.firebasestorage.app',
    measurementId: 'G-VV7Y61DM9G',
  );
}
